<a href="https://colab.research.google.com/github/Manthan26-cmd/BML/blob/main/EXPT_2_BML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [ ]:
data=pd.read_csv('/content/student-mat.csv')

In [ ]:
data.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [ ]:
print(data.isnull().sum())

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [ ]:
categorical_cols = ['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic']
data = pd.get_dummies(data, columns=categorical_cols, drop_first=True)

In [ ]:
numerical_cols = ['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
data[numerical_cols] = scaler.fit_transform(data[numerical_cols])

In [ ]:
print(data.head())

        age      Medu      Fedu  traveltime  studytime  failures    famrel  \
0  1.023046  1.143856  1.360371    0.792251  -0.042286 -0.449944  0.062194
1  0.238380 -1.600009 -1.399970   -0.643249  -0.042286 -0.449944  1.178860
2 -1.330954 -1.600009 -1.399970   -0.643249  -0.042286  3.589323  0.062194
3 -1.330954  1.143856 -0.479857   -0.643249   1.150779 -0.449944 -1.054472
4 -0.546287  0.229234  0.440257   -0.643249  -0.042286 -0.449944  0.062194

   freetime     goout      Dalc  ...  guardian_mother  guardian_other  \
0 -0.236010  0.801479 -0.540699  ...             True           False
1 -0.236010 -0.097908 -0.540699  ...            False           False
2 -0.236010 -0.997295  0.583385  ...             True           False
3 -1.238419 -0.997295 -0.540699  ...             True           False
4 -0.236010 -0.997295 -0.540699  ...            False           False

   schoolsup_yes  famsup_yes  paid_yes  activities_yes  nursery_yes  \
0           True       False     False           False         True
1          False        True     False           False        False
2           True       False      True           False         True
3          False        True      True            True         True
4          False        True      True           False         True

   higher_yes  internet_yes  romantic_yes
0        True         False         False
1        True          True         False
2        True          True         False
3        True          True          True
4        True         False         False

[5 rows x 42 columns]